apiVersion: v1
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3SGhjTk1qWXdNekl5TWpBek5URTFXaGNOTXpZd016SXpNakF6TlRFMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQ2tIaU1memtTVEI5RWZ6WWVRSzNhMjA1NytRSVFacGxhdGpiZmZlUWIKYytuK2FGc3hnWmI3ckFiRlR4WU40cnN4MlRJRVVKcFExQVlicmtYRHdad1hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWlkUXl6RmVsTHAwSzBHZDAzdnNSCmVIUmp1dWt3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQXB2bFRSMkorWkFmRXJzK2wzWHZZbjREckliV1V5dzAKWjlocGFUT1llVUVDSUU3WlhLOGZIRm44OWlRSkpIenF6T2YyUm81NU1rV09rZkZqTkVMRUZhQUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc1ODUwOTA2LCJpYXQiOjE3NzU4NDczMDYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYjljYTQxZTUtNmZmOC00MGM1LWIzOGMtMjRhOTUwNzRiMGExIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6IjlkZGY0ODMxLTczNmUtNGZkMy04NmZiLTUwMzk1MmUyOWVjNiJ9fSwibmJmIjoxNzc1ODQ3MzA2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.DBVuy6z9wrUyABH_Sv9266Q5VFHzOWWP_CBxedN7PWg-yYx5ccy--2AEsbo0NSsLBeOorx4wsUrHGaowUkzYWgz-OxD_4nm9un8xSCNBKIoPUFEIwXY2TpkEmACnbIZ7zzPHcgTjqeqV-HvroxW0B7nAQGuNRv9kYfBYBpC1H6uDphAfkawUpy9dA46MTHKa3hsBb9ztX76q5fSyVEVIKLfbdmH-VR9PsubWyxF3VbuaKaLORBUjSbHgBmZvz3hyblsNTGzBiJ6W1wpGWDMShvsBn112mPzLLlI5nSXGbgGF3FUPErZ52O9o-ltfGkZA6NIpjjOOAJIyHYMDhbIjUg

contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context
